name: Tests

on:
  push:
    branches:
      - main
    paths:
      - 'bucket/**'
  pull_request:
    paths:
      - 'bucket/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Validate manifests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
