name: Excavator

on:
  schedule:
    - cron: '20 */6 * * *'
  workflow_dispatch:

concurrency:
  group: excavator
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Excavate
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
